
spring:
    datasource:
      #url: jdbc:postgresql://localhost:5432/pos #For local
      url: jdbc:postgresql://db:5432/pos #For docker
      username: postgres
      password: password
      hikari:
        connectionTimeout: 20000
        maximumPoolSize: 5

#spring:
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 9000

logging:
  level:
    .: error
    com.pos: TRACE
    org.springframework: ERROR