
spring:
    profiles:
      active: local

#spring:
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 9000

logging:
  level:
    .: error
    com.pos: TRACE
    org.springframework: ERROR