version: "3.3"

services:
  web:
    image: pos-1.0
    expose:
      - "9000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.config:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "8090:8090"