version: "3.3"

services:
  web:
    image: pos:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db
    expose:
      - "9000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.config:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "8090:8090"
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./../../data/data-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  db2:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./../../data/data-postgres-9:/var/lib/postgresql/data
    ports:
      - 5433:5432