-- To list databases
-- \l
-- To switch database
-- \c <database name>
-- To list tables
-- dt

CREATE DATABASE pos;
\c pos;
CREATE TABLE inventory (id INT GENERATED BY DEFAULT AS IDENTITY, barcode VARCHAR NOT NULL, price INT NOT NULL);
INSERT INTO inventory (barcode, price) VALUES ('12345', 1250);