spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/pos #For local
    #url: jdbc:postgresql://db:5432/pos #For docker
    url: jdbc:postgresql://10.100.0.1:5432/pos #using cluster ip instead not sure why service name suddenly unable to connect
    #jdbc:postgresql://db-service:5432/pos #For k8s
    username: postgres
    password: password
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5